### ISSUE TITLE
not work in hexo 3.1.1

### ISSUE THREAD

**Issue by zhuyifan2013** [jysperm/hexo-theme-simpleblock#2]
hexo: 3.1.1
os: Linux 3.13.0-37-generic linux x64
http_parser: 2.3
node: 0.12.7
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1p

wrong info is :
extends base block head if is_tag() title æ ‡ç­¾ï¼š#{page.tag} | #{config.title} else if page.category title åˆ†ç±»ï¼š#{page.category} | #{config.title} else if page.year && page.month title å½’æ¡£ï¼š#{page.year} å¹´ #{page.month} æœˆ | #{config.title} else if !page.posts title #{page.title} | #{config.title} else title= config.title mixin article(post) article header if page.posts h2 a(href=url_for(post.path))= post.title else small.right a(target='_blank', href=sourceOfPost(post, theme.source_url)) æŸ¥çœ‹æºä»£ç  h2= post.title .article-meta.clearfix time.left= post.date.format(config.date_format) if post.categories ul.tags.left - post.categories.each(function(category) { li a(href=url_for(category.path))= category.name - }); if post.tags ul.tags.right - post.tags.each(function(tag) { li a(href=url_for(tag.path))= tag.name - }); .markdown-body!= post.content if !page.posts && theme.duoshuo .ds-thread(data-thread-key=duoshuoKey(post), data-title=post.title, data-url=post.permalink) block body for banner in formatArray(theme.banners) .archive-title +widget-inter(banner) if is_tag() .archive-title strong æ ‡ç­¾ ##{page.tag} if page.category .archive-title strong åˆ†ç±» ##{page.category} if page.year && page.month .archive-title strong å½’æ¡£ #{page.year} å¹´ #{page.month} æœˆ if page.posts - page.posts.each(function(post) { +article(post) - }); .archive-pagination .paginator!= fixPaginator(paginator({prev_text: '«', next_text: '»'})) else +article(page)

**Comment by jysperm** [comment]
是否是忘记安装 hexo-renderer-jade 了？试一试 `npm install hexo-renderer-jade --save`

**Comment by zhuyifan2013** [comment]
OK 已解决
