### ISSUE TITLE
不能去掉 banner 和 widget的markdown区域

### ISSUE THREAD

**Issue by zhuyifan2013** [jysperm/hexo-theme-simpleblock#3]
去掉之后就会报错

**Comment by LINCHUAN114** [comment]
来自我的华为手机-------- 原始邮件 --------主题：[hexo-theme-simpleblock] 不能去掉 banner 和 widget的markdown区域 (#3)发件人：Yifan Zhu 收件人：jysperm/hexo-theme-simpleblock 抄送：去掉之后就会报错

**Comment by jysperm** [comment]
感谢关注，这确实是一个 Bug, 我发布了一个新版本来解决这个问题，你可以这样来更新：

```
# 如果你修改过 simpleblock, 请在删除前备份
rm -r themes/simpleblock
npm install hexo-theme-simpleblock
mv node_modules/hexo-theme-simpleblock themes/simpleblock
```
