### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by shliujing** [jysperm/hexo-theme-simpleblock#5]
对比了很多个主题，觉得博主的主题不错。
只是部署的时候，一堆乱码，望能够继续完善。
![2015-10-06_203802](https://cloud.githubusercontent.com/assets/7680598/10308818/0aa24662-6c6b-11e5-8305-46e244f5fca7.png)

**Comment by jysperm** [comment]
是否是忘记安装 hexo-renderer-jade 了？试一试 `npm install hexo-renderer-jade --save`

**Comment by shliujing** [comment]
已解决。
的确是这个问题导致的。
之前命令敲了，应该是目录操作没操作好。
thx！
