### ISSUE TITLE
formatArray问题请教

### ISSUE THREAD

**Issue by tufu9441** [jysperm/hexo-theme-simpleblock#6]
您好，我正在修改一个Hexo的模板，见这里[Maupassant-hexo](https://github.com/tufu9441/maupassant-hexo)，我想把侧边栏的widgets像您的主题一样可以在配置文件中进行添加和选择，但是大概仿照着试了一下没能成功，主要是hexo server的时候会报错`for item in formatArray(theme.widgets)`这一行"undefined is not a function"，我搜索了一下也没能找到这个formatArray的具体用法，还请不吝赐教！

**Comment by jysperm** [comment]
formatArray 是我在这里实现的： https://github.com/jysperm/hexo-theme-simpleblock/blob/04db4bd99fe53bd5054a6b4dc0d1d99bd5013c29/helpers.coffee#L5
